name: cd_test
on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  deploy:
    name: cd_test
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          key: ${{ secrets.EC2_SECRET_KEY }}
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.SSH_ID }}
          script: |
            cd ${{ secrets.UBUNTU_PATH }}
            sudo git pull origin main
            sudo npm install
            sudo pm2 restart app.js
